#spring:
#  application:
#    name: rate
#
#---
#spring:
#  profiles: zone1
#eureka:
#  instance:
#    metadata-map:
#      zone: zone1
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: ${PORT:7000}
#---
#spring:
#  profiles: zone2
#eureka:
#  instance:
#    metadata-map:
#      zone: zone2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#server:
#  port: ${PORT:1001}