# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 1000
eureka:
  instance:
    hostname: default-eureka-server.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    peer-eureka-nodes-update-interval-ms: 2000
#    peer-node-connect-timeout-ms: 900000
#    enable-self-preservation: false

---
spring:
  profiles: eureka-1
  application:
    name: eureka-server-clustered
server:
  port: 1005
eureka:
  instance:
    hostname: eureka-1-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.20:1002/eureka/,http://eureka-3-server.com:1003/eureka/
#     defaultZone: http://localhost:1002/eureka/,http://eureka-3-server.com:1003/eureka/
#  server:
#    peer-eureka-nodes-update-interval-ms: 2000
#    peer-node-connect-timeout-ms: 900000
#    enable-self-preservation: false

---
spring:
  profiles: eureka-2
  application:
    name: eureka-server-clustered
server:
  port: 1002
eureka:
  instance:
    hostname: eureka-2-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-1-server.com:1005/eureka/,http://eureka-3-server.com:1003/eureka/
#  server:
#    peer-eureka-nodes-update-interval-ms: 2000
#    peer-node-connect-timeout-ms: 900000
#    enable-self-preservation: false

---
spring:
  profiles: eureka-3
  application:
    name: eureka-server-clustered
server:
  port: 1003
eureka:
  instance:
    hostname: peer-3-server.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-1-server.com:1005/eureka/,http://192.168.1.20:1002/eureka/
#  server:
#    peer-eureka-nodes-update-interval-ms: 2000
#    peer-node-connect-timeout-ms: 900000
#    enable-self-preservation: false
#      defaultZone: http://eureka-1-server.com:1005/eureka/,http://localhost:1002/eureka/




